[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "node-rs-jieba"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
jieba-rs = {version = "0.6", features = ["default-dict", "tfidf", "textrank"]}
napi = "2"
napi-derive = "1"
once_cell = "1.5"

[target.'cfg(all(target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1.1.0"
