[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "node-rs-crc32"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
crc32c = {version = "0.6"}
crc32fast = {version = "1.2", features = ["nightly"]}
napi = "2"
napi-derive = "1"

[target.'cfg(all(target_arch = "x86_64", not(target_env = "musl")))'.dependencies]
mimalloc = {version = "0.1"}

[build-dependencies]
napi-build = "1"
